package impdef

import (
	"bufio"
	"fmt"
	"io"
	"sort"
)

// Item is one entry of one of the two delegated lists.
//
// The statement template needs every item ISO defines, not only the ones this
// harness probes, so it takes the lists as data rather than deriving them from
// the observations. A caller builds these from the vendored catalogue.
type Item struct {
	Code        string
	Description string
	// Kind is Defined or Dependent. An Item is never an Extension: extensions
	// have no ISO item of their own and are printed from the observations.
	Kind Kind
}

// Statement is what WriteStatement needs to know beyond the items themselves.
type Statement struct {
	// Engine and Version name the implementation the answers were observed on.
	Engine, Version string
	// Observed is when, in whatever form the caller wants printed.
	Observed string
	// Source is where the reader can find the run these answers came from.
	Source string
}

// WriteStatement renders a Clause 24.5.2 conformance statement template.
//
// This is the artifact the whole package exists for. ISO does not ask an
// implementer for a percentage; 24.5.2 asks them to state, item by item, what
// their implementation chose, and 24.5.3 asks them to say what they added. The
// output below is that document with every item ISO defines already in it, in
// code order, each carrying the standard's own words, and with the answers this
// harness could observe already filled in beside the statement that observed
// them. What is left is what the vendor has to answer themselves, and it is
// marked with the same em dash an unavailable measurement gets.
//
// Nothing here is a claim that the vendor's statement is true. Every filled-in
// answer names the statement that produced it precisely so that the vendor can
// re-run it and disagree before signing anything.
func WriteStatement(w io.Writer, s Statement, items []Item, r *Result) error {
	b := bufio.NewWriter(w)
	defer func() { _ = b.Flush() }()
	p := func(format string, args ...any) { fmt.Fprintf(b, format, args...) }

	byItem := map[string][]Observation{}
	for _, o := range r.Observations {
		byItem[o.Item] = append(byItem[o.Item], o)
	}

	defined, dependent := split(items)

	p("# Implementation-defined and implementation-dependent behaviour\n\n")
	p("## About this document\n\n")
	p("ISO/IEC 39075:2024 Clause 24.5.2 requires an implementation claiming conformance to state what it chose " +
		"for each behaviour the standard leaves implementation-defined. Clause 24.5.3 permits extensions provided " +
		"the implementation documents them. This is a template for both, generated by gql-compat: it carries every " +
		"item the standard defines, in code order, with the standard's own description of each, and with the answers " +
		"one measured run was able to observe already filled in.\n\n")
	p("| | |\n|---|---|\n")
	p("| Implementation | %s |\n", or(s.Engine, "—"))
	p("| Version | %s |\n", or(s.Version, "—"))
	p("| Answers observed | %s |\n", or(s.Observed, "—"))
	if s.Source != "" {
		p("| From the run | `%s` |\n", s.Source)
	}
	p("| Items to state | %d implementation-defined |\n", len(defined))
	p("| Of which observed here | %d |\n", r.Observed(Defined))
	p("\n")
	p("**An observed answer is not a statement until you have checked it.** Every filled-in row names the statement " +
		"that produced the answer. Run it, disagree with it if it is wrong for your engine, and replace it. " +
		"Every remaining row is an em dash, which means this harness observed nothing and never means none, " +
		"unlimited or zero.\n\n")

	p("## Implementation-defined behaviour (24.5.2)\n\n")
	p("| Item | What the standard leaves to the implementation | This implementation | Observed by |\n")
	p("|---|---|---|---|\n")
	for _, it := range defined {
		writeRows(b, it, byItem[it.Code])
	}
	p("\n")

	p("## Implementation-dependent behaviour\n\n")
	p("The standard does not require any of this to be stated and no portable program may depend on it. " +
		"It is here because an answer observed once is worth writing down beside the answer nobody promised, " +
		"and because a reader who finds an engine's own documentation making a promise about one of these items " +
		"has found a promise the standard did not ask for.\n\n")
	p("| Item | What the standard leaves to the running system | Observed once | Observed by |\n")
	p("|---|---|---|---|\n")
	for _, it := range dependent {
		writeRows(b, it, byItem[it.Code])
	}
	p("\n")

	exts := r.Of(Extension)
	p("## Extensions (24.5.3)\n\n")
	if len(exts) == 0 {
		p("No extension was probed on this run. That is not a statement that the implementation has none.\n\n")
		return b.Flush()
	}
	p("Language the standard does not define, which 24.5.3 permits an implementation to accept provided it " +
		"documents the extension. The item cited beside each is IE005, the treatment of language that does not " +
		"conform to the Formats and Syntax Rules, which is itself implementation-defined.\n\n")
	p("| Extension | This implementation | Observed by | Why the standard does not define it |\n")
	p("|---|---|---|---|\n")
	for _, o := range exts {
		p("| %s | %s | %s | %s |\n",
			cell(o.Question), cell(o.Cell()), Code(o.Statement), cell(o.Note))
	}
	p("\n")
	return b.Flush()
}

// writeRows prints one item, which is one row when nothing probed it and one
// row per probe when something did. Two probes of one item are two answers to
// one question and collapsing them would drop one of them.
func writeRows(b io.Writer, it Item, obs []Observation) {
	p := func(format string, args ...any) { fmt.Fprintf(b, format, args...) }
	if len(obs) == 0 {
		p("| `%s` | %s | — | — |\n", it.Code, cell(it.Description))
		return
	}
	for _, o := range obs {
		p("| `%s` | %s | %s | %s |\n",
			it.Code, cell(it.Description), cell(o.Cell()), Code(o.Statement))
	}
}

func split(items []Item) (defined, dependent []Item) {
	for _, it := range items {
		switch it.Kind {
		case Dependent:
			dependent = append(dependent, it)
		default:
			defined = append(defined, it)
		}
	}
	sort.Slice(defined, func(i, j int) bool { return defined[i].Code < defined[j].Code })
	sort.Slice(dependent, func(i, j int) bool { return dependent[i].Code < dependent[j].Code })
	return defined, dependent
}

func or(s, fallback string) string {
	if s == "" {
		return fallback
	}
	return s
}
